stages:
  - build
  - test
  - deploy

# Build Stage
build:
  stage: build
  image: python:3.8
  script:
    - python -m venv env
    - source env/bin/activate
    - pip install -r requirements.txt

# Test Stage
test:
  stage: test
  image: python:3.8
  script:
    - source env/bin/activate
    - pytest
  artifacts:
    paths:
      - coverage/

# Deploy Stage
deploy:
  stage: deploy
  image: node:16 # Use a suitable image for Vercel CLI
  script:
    - npm install -g vercel # Install Vercel CLI
    - vercel --prod --token $your_tokey_key # Deploy to production
  only:
    - main
